#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://113.45.0.33:9000
  accessKey: wanzx11
  secretKey: 555888ww
